# Generated by Django 4.2.27 on 2025-12-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id_tercero', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=45, null=True)),
                ('es_cliente', models.CharField(default='N', max_length=1)),
                ('es_proveedor', models.CharField(default='N', max_length=1)),
                ('es_empleado', models.CharField(default='N', max_length=1)),
                ('es_usuario', models.CharField(default='N', max_length=1)),
                ('password', models.CharField(blank=True, db_column='clave', max_length=45, null=True)),
                ('usuario', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('id_tercero_registra', models.IntegerField(blank=True, null=True)),
                ('fch_registro', models.DateTimeField(auto_now_add=True)),
                ('ejecuta_labor_tecnica', models.CharField(default='N', max_length=1)),
                ('super_usuario', models.CharField(default='N', max_length=1)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'tercero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(blank=True, max_length=80, null=True)),
                ('id_estado_actividad', models.IntegerField(db_column='id_estado_actividad')),
                ('direccion', models.CharField(max_length=80)),
                ('fch_actividad', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=13, max_digits=16)),
                ('longitud', models.DecimalField(decimal_places=13, max_digits=16)),
                ('seq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoLuminaria',
            fields=[
                ('id_estado_luminaria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_luminaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPqr',
            fields=[
                ('id_estado_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('permitir_edicion', models.CharField(max_length=1)),
                ('permitir_eliminar', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'estado_pqr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Luminaria',
            fields=[
                ('id_luminaria', models.AutoField(primary_key=True, serialize=False)),
                ('poste_no', models.CharField(max_length=45)),
                ('luminaria_no', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=45)),
                ('latitud', models.DecimalField(decimal_places=13, max_digits=16)),
                ('longitud', models.DecimalField(decimal_places=13, max_digits=16)),
                ('referencia', models.CharField(blank=True, max_length=45, null=True)),
                ('fch_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'luminaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedioRecepcionPqr',
            fields=[
                ('id_medio_recepcion_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'medio_recepcion_pqr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('tiene_contrato', models.CharField(max_length=1)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('id_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fch_registro', models.DateTimeField()),
                ('fch_pqr', models.DateField()),
                ('fch_cierre', models.DateTimeField(blank=True, null=True)),
                ('direccion_reporte', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre_usuario_servicio', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'pqr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id_tipo_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('instalacion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tipo_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tipo_identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('abreviatura', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
                'db_table': 'tipo_identificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLuminaria',
            fields=[
                ('id_tipo_luminaria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tipo_luminaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPqr',
            fields=[
                ('id_tipo_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('dias_vencimiento', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tipo_pqr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_reporte',
                'managed': False,
            },
        ),
    ]
