# Generated by Django 5.2.8 on 2026-02-24 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('clase', models.CharField(db_comment='S:SERVICIO M:MATERIAL', max_length=1)),
            ],
            options={
                'db_table': 'articulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadMobile',
            fields=[
                ('id_actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mobile_data', serialize=False, to='core.actividad')),
                ('fch_inicio', models.DateTimeField(blank=True, null=True)),
                ('latitud_inicio', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('longitud_inicio', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
            ],
            options={
                'db_table': 'actividad_mobile',
            },
        ),
        migrations.CreateModel(
            name='ActividadFirma',
            fields=[
                ('id_actividad_firma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_firmante', models.CharField(max_length=100)),
                ('firma_base64', models.TextField()),
                ('fch_registro', models.DateTimeField(auto_now_add=True)),
                ('id_actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='core.actividad')),
            ],
            options={
                'db_table': 'actividad_firma',
            },
        ),
        migrations.CreateModel(
            name='ActividadFoto',
            fields=[
                ('id_actividad_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='actividades/fotos/')),
                ('tipo', models.CharField(choices=[('ANTES', 'Antes'), ('DESPUES', 'Después')], max_length=10)),
                ('fch_registro', models.DateTimeField(auto_now_add=True)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.actividad')),
            ],
            options={
                'db_table': 'actividad_foto',
            },
        ),
        migrations.CreateModel(
            name='ActividadMaterial',
            fields=[
                ('id_actividad_material', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('INSTALADO', 'Instalado'), ('DESMONTADO', 'Desmontado')], max_length=20)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.actividad')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.articulo')),
            ],
            options={
                'db_table': 'actividad_material',
            },
        ),
    ]
