# Generated by Django 4.2.27 on 2026-03-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articulo_actividadmobile_actividadfirma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('id_estado_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unitario', models.AutoField(db_column='id_unidad_medida', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'unidad_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='actividadmaterial',
            name='id_unidad_medida',
            field=models.ForeignKey(blank=True, db_column='id_unidad_medida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.unidadmedida'),
        ),
    ]
